version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=6GnuPpaP4oH-tpFKOFYBG
      - MYSQL_DATABASE=promas
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=G6XJSnmlDUG4IOemyJAeb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"